# Generated by Django 4.2.16 on 2024-11-24 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0003_alter_product_old_price'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=111)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
