# Generated by Django 4.2.16 on 2024-11-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0003_alter_product_old_price'),
        ('user_app', '0002_cartmodles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModles',
            new_name='CartModels',
        ),
    ]
